const express=require('express');const {getPool,sql}=require('../../config/db');const audit=require('../../services/audit');const router=express.Router();
function admin(req){return req.user.permissions.includes('USUARIOS_ADMINISTRAR')||req.user.permissions.includes('ADMIN_TOTAL')}
router.get('/usuarios',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const p=await getPool();const r=await p.request().query(`SELECT u.UsuarioId,u.NombreUsuario,u.Correo,u.Activo,u.UltimoAcceso,u.BloqueadoHasta,u.DebeCambiarPassword,STRING_AGG(r.Nombre,', ') Roles FROM Usuarios u LEFT JOIN UsuarioRoles ur ON ur.UsuarioId=u.UsuarioId AND ur.Activo=1 LEFT JOIN Roles r ON r.RolId=ur.RolId GROUP BY u.UsuarioId,u.NombreUsuario,u.Correo,u.Activo,u.UltimoAcceso,u.BloqueadoHasta,u.DebeCambiarPassword ORDER BY u.UsuarioId`);res.json({ok:true,rows:r.recordset});}catch(e){next(e)}});
router.patch('/usuarios/:id/toggle',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const p=await getPool();await p.request().input('id',sql.Int,req.params.id).query('UPDATE Usuarios SET Activo=CASE WHEN Activo=1 THEN 0 ELSE 1 END WHERE UsuarioId=@id');await audit(req,{module:'USUARIOS',action:'ACTIVAR_DESACTIVAR',operation:'UPDATE',recordId:req.params.id});res.json({ok:true});}catch(e){next(e)}});
router.get('/roles-list',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const p=await getPool();const r=await p.request().query(`SELECT r.RolId,r.Nombre,r.Activo,COUNT(CASE WHEN ur.Activo=1 THEN 1 END) CantidadUsuarios FROM Roles r LEFT JOIN UsuarioRoles ur ON ur.RolId=r.RolId GROUP BY r.RolId,r.Nombre,r.Activo ORDER BY r.Nombre`);res.json({ok:true,roles:r.recordset});}catch(e){next(e)}});
router.post('/roles',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const nombre=String(req.body?.nombre||'').trim();if(!nombre)return res.status(400).json({ok:false,message:'El nombre del rol es obligatorio.'});const p=await getPool();const exists=await p.request().input('n',sql.NVarChar(80),nombre).query('SELECT RolId FROM Roles WHERE LOWER(Nombre)=LOWER(@n)');if(exists.recordset.length)return res.status(400).json({ok:false,message:'Ya existe un rol con ese nombre.'});const r=await p.request().input('n',sql.NVarChar(80),nombre).query(`INSERT Roles(Nombre,Descripcion,Activo) OUTPUT INSERTED.RolId,INSERTED.Nombre VALUES(@n,NULL,1)`);await audit(req,{module:'ROLES',action:'CREAR_ROL',operation:'INSERT',recordId:r.recordset[0].RolId,newValues:{Nombre:nombre}});res.json({ok:true,rol:r.recordset[0]});}catch(e){next(e)}});
router.get('/roles',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const p=await getPool();const rs=await p.request().query('SELECT * FROM Roles ORDER BY Nombre; SELECT * FROM Permisos ORDER BY Modulo,Codigo; SELECT rp.RolId,rp.PermisoId FROM RolPermisos rp');res.json({ok:true,roles:rs.recordsets[0],permisos:rs.recordsets[1],asignaciones:rs.recordsets[2]});}catch(e){next(e)}});
router.post('/roles/:rolId/permisos/:permisoId',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const p=await getPool();await p.request().input('r',sql.Int,req.params.rolId).input('p',sql.Int,req.params.permisoId).query(`IF EXISTS(SELECT 1 FROM RolPermisos WHERE RolId=@r AND PermisoId=@p) DELETE RolPermisos WHERE RolId=@r AND PermisoId=@p ELSE INSERT RolPermisos(RolId,PermisoId) VALUES(@r,@p)`);await audit(req,{module:'ROLES',action:'CAMBIAR_PERMISO',operation:'UPDATE',recordId:req.params.rolId});res.json({ok:true});}catch(e){next(e)}});
router.post('/usuarios/:uid/roles/:rid',async(req,res,next)=>{try{if(!admin(req))return res.status(403).json({ok:false});const p=await getPool();await p.request().input('u',sql.Int,req.params.uid).input('r',sql.Int,req.params.rid).query(`IF EXISTS(SELECT 1 FROM UsuarioRoles WHERE UsuarioId=@u AND RolId=@r) UPDATE UsuarioRoles SET Activo=CASE WHEN Activo=1 THEN 0 ELSE 1 END WHERE UsuarioId=@u AND RolId=@r ELSE INSERT UsuarioRoles(UsuarioId,RolId,Activo) VALUES(@u,@r,1)`);await audit(req,{module:'USUARIOS',action:'CAMBIAR_ROL',operation:'UPDATE',recordId:req.params.uid});res.json({ok:true});}catch(e){next(e)}});
module.exports=router;
