const express=require('express');const modules=require('../../config/modules');const repo=require('../../repositories/genericRepository');const {permit}=require('../../middleware/auth');const audit=require('../../services/audit');
const router=express.Router();
router.param('module',(req,res,next,name)=>{req.meta=modules[name];if(!req.meta)return res.status(404).json({ok:false,message:'Módulo no existe.'});req.moduleName=name;next();});
router.get('/:module',async(req,res,next)=>{try{const m=req.meta;if(!req.user.permissions.includes(m.permission+'_CONSULTAR')&&!req.user.permissions.includes('ADMIN_TOTAL'))return res.status(403).json({ok:false,message:'Sin permiso.'});const data=await repo.list(m,{q:req.query.q||'',page:Number(req.query.page||1),pageSize:25});res.json({ok:true,...data});}catch(e){next(e)}});
router.get('/:module/:id',async(req,res,next)=>{try{const m=req.meta;if(!req.user.permissions.includes(m.permission+'_CONSULTAR')&&!req.user.permissions.includes('ADMIN_TOTAL'))return res.status(403).json({ok:false,message:'Sin permiso.'});res.json({ok:true,data:await repo.get(m,req.params.id)});}catch(e){next(e)}});
router.post('/:module',async(req,res,next)=>{try{const m=req.meta;if(!req.user.permissions.includes(m.permission+'_REGISTRAR')&&!req.user.permissions.includes('ADMIN_TOTAL'))return res.status(403).json({ok:false,message:'Sin permiso.'});const id=await repo.insert(m,req.body);await audit(req,{module:m.title,action:'REGISTRAR',operation:'INSERT',recordId:id,after:req.body});res.json({ok:true,id,message:'Registro guardado.'});}catch(e){next(e)}});
router.put('/:module/:id',async(req,res,next)=>{try{const m=req.meta;if(!req.user.permissions.includes(m.permission+'_MODIFICAR')&&!req.user.permissions.includes('ADMIN_TOTAL'))return res.status(403).json({ok:false,message:'Sin permiso.'});const before=await repo.get(m,req.params.id);if(req.moduleName==='ordenes'&&['FINALIZADA','FACTURADA','ENTREGADA','CANCELADA'].includes(before?.Estado)&&!req.user.permissions.includes('ORDENES_MODIFICAR_FINALIZADA')&&!req.user.permissions.includes('ADMIN_TOTAL'))return res.status(403).json({ok:false,message:'La orden está cerrada y requiere autorización especial para modificarse.'});await repo.update(m,req.params.id,req.body);await audit(req,{module:m.title,action:'MODIFICAR',operation:'UPDATE',recordId:req.params.id,before,after:req.body});res.json({ok:true,message:'Registro actualizado.'});}catch(e){next(e)}});
router.patch('/:module/:id/toggle',async(req,res,next)=>{try{const m=req.meta;if(!req.user.permissions.includes(m.permission+'_DESACTIVAR')&&!req.user.permissions.includes('ADMIN_TOTAL'))return res.status(403).json({ok:false,message:'Sin permiso.'});await repo.deactivate(m,req.params.id);await audit(req,{module:m.title,action:'ACTIVAR_DESACTIVAR',operation:'UPDATE',recordId:req.params.id});res.json({ok:true,message:'Estado actualizado.'});}catch(e){next(e)}});
module.exports=router;
