const f=(name,label,type='text',required=false)=>({name,label,type,required});
module.exports={
 clientes:{title:'Clientes',table:'Clientes',pk:'ClienteId',permission:'CLIENTES',search:['NombreRazonSocial','Identificacion','Telefono','Correo'],fields:[f('TipoCliente','Tipo cliente'),f('NombreRazonSocial','Nombre / razón social','text',true),f('Identificacion','Identificación','text',true),f('Telefono','Teléfono'),f('Correo','Correo','email'),f('Direccion','Dirección'),f('Activo','Activo','checkbox')]},
 empleados:{title:'Empleados',table:'Empleados',pk:'EmpleadoId',permission:'EMPLEADOS',search:['Identificacion','NombreCompleto','Correo'],fields:[f('Identificacion','Identificación','text',true),f('NombreCompleto','Nombre completo','text',true),f('Telefono','Teléfono'),f('Correo','Correo','email'),f('Direccion','Dirección'),f('FechaContratacion','Fecha contratación','date'),f('Especialidad','Especialidad'),f('EstadoLaboral','Estado laboral'),f('UsuarioId','Usuario asociado','number')]},
 marcas:{title:'Marcas de vehículo',table:'MarcasVehiculo',pk:'MarcaId',permission:'CATALOGOS',search:['Nombre'],fields:[f('Nombre','Nombre','text',true),f('Activo','Activo','checkbox')]},
 modelos:{title:'Modelos de vehículo',table:'ModelosVehiculo',pk:'ModeloId',permission:'CATALOGOS',search:['Nombre'],fields:[f('MarcaId','Marca ID','number',true),f('Nombre','Modelo','text',true),f('Activo','Activo','checkbox')]},
 tiposvehiculo:{title:'Tipos de vehículo',table:'TiposVehiculo',pk:'TipoVehiculoId',permission:'CATALOGOS',search:['Nombre'],fields:[f('Nombre','Nombre','text',true),f('Activo','Activo','checkbox')]},
 combustibles:{title:'Tipos de combustible',table:'TiposCombustible',pk:'TipoCombustibleId',permission:'CATALOGOS',search:['Nombre'],fields:[f('Nombre','Nombre','text',true),f('Activo','Activo','checkbox')]},
 categoriasvehiculo:{title:'Categorías de vehículos',table:'CategoriasVehiculo',pk:'CategoriaVehiculoId',permission:'CATALOGOS',search:['Nombre'],fields:[f('Nombre','Nombre','text',true),f('Activo','Activo','checkbox')]},
 vehiculos:{title:'Vehículos',table:'Vehiculos',pk:'VehiculoId',permission:'VEHICULOS',search:['Placa','VIN','Color'],fields:[f('ClienteId','Cliente','number',true),f('Placa','Placa (ej. ABC123)','text',true),f('VIN','VIN (ej. 1HGCM82633A004352)','text',true),f('ModeloId','Modelo','number',true),f('TipoVehiculoId','Tipo de vehículo','number',true),f('TipoCombustibleId','Combustible','number',true),f('CategoriaVehiculoId','Categoría','number'),f('Anio','Año','number'),f('Color','Color'),f('CilindrajeCC','Cilindraje cc','number'),f('KilometrajeActual','Kilometraje','number'),f('FechaIngreso','Fecha ingreso','date'),f('Observaciones','Observaciones'),f('Activo','Activo','checkbox')]},
 servicios:{title:'Servicios',table:'Servicios',pk:'ServicioId',permission:'SERVICIOS',search:['Codigo','Nombre','Descripcion'],fields:[f('Codigo','Código','text',true),f('Nombre','Nombre','text',true),f('Descripcion','Descripción'),f('Categoria','Categoría'),f('PrecioBase','Precio base','number',true),f('TiempoEstimadoMinutos','Tiempo estimado (min)','number',true),f('PorcentajeImpuesto','Impuesto %','number'),f('Activo','Activo','checkbox')]},
 productos:{title:'Productos y repuestos',table:'Productos',pk:'ProductoId',permission:'PRODUCTOS',search:['CodigoInterno','CodigoBarras','Nombre'],fields:[f('CodigoInterno','Código interno','text',true),f('CodigoBarras','Código de barras'),f('Nombre','Nombre','text',true),f('Descripcion','Descripción'),f('Categoria','Categoría'),f('Marca','Marca'),f('UnidadMedida','Unidad medida'),f('PrecioCompra','Precio compra','number'),f('PrecioVenta','Precio venta','number'),f('PorcentajeImpuesto','Impuesto %','number'),f('ExistenciaActual','Existencia actual','number'),f('ExistenciaMinima','Existencia mínima','number'),f('ExistenciaMaxima','Existencia máxima','number'),f('Ubicacion','Ubicación'),f('ProveedorPrincipalId','Proveedor principal ID','number'),f('TipoProducto','Tipo producto'),f('Activo','Activo','checkbox')]},
 proveedores:{title:'Proveedores',table:'Proveedores',pk:'ProveedorId',permission:'PROVEEDORES',search:['Identificacion','NombreRazonSocial','Correo'],fields:[f('TipoIdentificacion','Tipo identificación'),f('Identificacion','Identificación','text',true),f('NombreRazonSocial','Nombre / razón social','text',true),f('Telefono','Teléfono'),f('Correo','Correo','email'),f('Direccion','Dirección'),f('ContactoPrincipal','Contacto principal'),f('CondicionesPago','Condiciones de pago'),f('Activo','Activo','checkbox')]},
 citas:{title:'Agenda y citas',table:'Citas',pk:'CitaId',permission:'CITAS',search:['Observaciones'],fields:[f('ClienteId','Cliente','number',true),f('VehiculoId','Vehículo','number',true),f('FechaHoraInicio','Inicio','datetime-local',true),f('Observaciones','Observaciones')]},
 recepciones:{title:'Recepción de vehículos',table:'Recepciones',pk:'RecepcionId',permission:'RECEPCIONES',search:['NumeroRecepcion','MotivoVisita','Estado'],fields:[f('ClienteId','Cliente ID','number',true),f('VehiculoId','Vehículo ID','number',true),f('KilometrajeIngreso','Kilometraje','number',true),f('NivelCombustible','Nivel combustible'),f('MotivoVisita','Motivo'),f('ProblemaCliente','Problema indicado'),f('AccesoriosObjetos','Accesorios / objetos'),f('DanosVisibles','Daños visibles'),f('EmpleadoRecibeId','Empleado que recibe ID','number',true),f('FechaEstimadaEntrega','Entrega estimada','datetime-local'),f('Observaciones','Observaciones'),f('Estado','Estado')]},
 diagnosticos:{title:'Diagnósticos',table:'Diagnosticos',pk:'DiagnosticoId',permission:'DIAGNOSTICOS',search:['NumeroDiagnostico','ProblemasEncontrados','Estado'],fields:[f('RecepcionId','Recepción ID','number',true),f('ProblemasEncontrados','Problemas encontrados'),f('PruebasRealizadas','Pruebas realizadas'),f('PosiblesCausas','Posibles causas'),f('Recomendaciones','Recomendaciones'),f('ManoObraEstimada','Mano de obra estimada','number'),f('TiempoEstimadoMinutos','Tiempo reparación min','number'),f('CostoEstimado','Costo estimado','number'),f('MecanicoResponsableId','Mecánico responsable ID','number',true),f('Estado','Estado')]},
 cotizaciones:{title:'Cotizaciones',table:'Cotizaciones',pk:'CotizacionId',permission:'COTIZACIONES',search:['NumeroCotizacion','Estado'],fields:[f('DiagnosticoId','Diagnóstico','number',true),f('FechaVencimiento','Vencimiento','date',true),f('PrecioHoraManoObra','Precio por hora','number',true),f('DescuentoPorcentaje','Descuento %','number'),f('Condiciones','Condiciones'),f('Observaciones','Observaciones'),f('Estado','Estado')]},
 ordenes:{title:'Órdenes de trabajo',table:'OrdenesTrabajo',pk:'OrdenTrabajoId',permission:'ORDENES',search:['NumeroOrden','Estado','Prioridad'],fields:[f('CotizacionId','Cotización ID','number'),f('VehiculoId','Vehículo ID','number',true),f('ClienteId','Cliente ID','number',true),f('FechaEstimadaEntrega','Entrega estimada','datetime-local'),f('Prioridad','Prioridad'),f('Estado','Estado'),f('Observaciones','Observaciones')]},
 garantias:{title:'Garantías',table:'Garantias',pk:'GarantiaId',permission:'GARANTIAS',search:['TipoCobertura','Estado'],fields:[f('OrdenTrabajoId','Orden ID','number'),f('VentaId','Venta ID','number'),f('ProductoId','Producto ID','number'),f('ServicioId','Servicio ID','number'),f('TipoCobertura','Tipo cobertura'),f('FechaInicio','Inicio','date'),f('FechaVencimiento','Vencimiento','date'),f('Condiciones','Condiciones'),f('Estado','Estado'),f('Observaciones','Observaciones')]},
 configuracion:{title:'Configuración general',table:'ConfiguracionGeneral',pk:'ConfiguracionId',permission:'CONFIGURACION',search:['NombreTaller','IdentificacionJuridica'],fields:[f('NombreTaller','Nombre taller'),f('IdentificacionJuridica','Identificación jurídica'),f('Direccion','Dirección'),f('Telefono','Teléfono'),f('Correo','Correo','email'),f('LogotipoUrl','Logotipo URL'),f('PorcentajeImpuestoGeneral','Impuesto general %','number'),f('Moneda','Moneda'),f('FormatoRecepcion','Formato recepción'),f('FormatoCotizacion','Formato cotización'),f('FormatoOrden','Formato orden'),f('FormatoVenta','Formato venta'),f('FormatoFactura','Formato factura'),f('LimiteDescuento','Límite descuento %','number'),f('HorarioAtencion','Horario atención'),f('PlazoGarantiaDias','Garantía días','number'),f('ExistenciaMinimaPredeterminada','Existencia mínima','number')]}
};
